### ISSUE TITLE
Maybe it is time to create a team for this :)

### ISSUE THREAD

**Issue by chrisglass** [ubuntu-bartenders/ubuntu-old-fashioned#66]
I don't mind being the guardian of commit rights, but at this point most if not all of you have a better handle on the code.

How about I create a github team so y'all can manage commit rights yourself?

@philroche ?

**Comment by philroche** [comment]
You're it now @chrisglass no going back :)

Only joking. A team sounds great. Please do.

**Comment by chrisglass** [comment]
This is now done.

The new project's URL is therefore https://github.com/ubuntu-bartenders/ubuntu-old-fashioned !

I invited you @philroche as co-owner. Hurray for Old Fashioned cocktails :)

**Comment by philroche** [comment]
Awesome. Thank you

**Comment by philroche** [comment]
@chrisglass Can you transfer ownership to the new team so github will redirect and we don't lose issues?

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by chrisglass** [comment]
Now done :)

Hopefully, this looks right now, otherwise, just let me know.

**Comment by philroche** [comment]
Brilliant. Thanks again
